export const defaultPath="/"
export const lastTimeUpdated="/lastTimeUpdated"
export const currency="/currency"
export const addCurrencyInformation="/add"
export const getCurrencyValue="/value"
export const displayCurrency="/hide"
export const nameSort="/namesort"
export const valueSort="/valuesort"